"""Structured subprocess suites executed by the release selftest."""

import os
import subprocess


REFACTOR_SAFETY_SUITES = (
    ("稳定基线恢复能力契约",
     ("scripts/tests/test_stable_recovery_contract.py",), 90, 3000),
    ("Story 原模板与本地实施附录契约",
     ("scripts/tests/test_story_contract.py",), 90, 3000),
    ("项目本地启动器、资源与工作目录",
     ("scripts/tests/test_project_resources.py",), 90, 3000),
    ("本地 Spec 与领域文档边界",
     ("scripts/tests/test_local_spec.py",), 90, 3000),
    ("领域文档相关上下文",
     ("scripts/tests/test_behavior_baseline.py",), 90, 3000),
    ("领域文档索引与协调",
     ("scripts/tests/test_domain_docs.py",), 90, 3000),
    ("Lean workflow state contract",
     ("scripts/tests/test_lean_state.py",), 90, 3000),
    ("Lean workflow migration contract",
     ("scripts/tests/test_lean_migration.py",), 90, 3000),
    ("Lean delivery manifest boundary",
     ("scripts/tests/test_delivery_manifest.py",), 90, 3000),
    ("Lean safety kernel boundary",
     ("scripts/tests/test_lean_safety_kernel.py",), 90, 3000),
    ("Gate 规则总账红线(无残留/无死锁)",
     ("scripts/tests/test_gate_rule_contract.py",), 90, 3000),
    ("Gate 非阻断提示送达通道",
     ("scripts/tests/test_gate_advisories.py",), 90, 3000),
    ("Spec2Code 固定 Prompt 与注释规范",
     ("scripts/tests/test_spec2code_prompt_resources.py",), 180, 5000),
    ("Spec2Code 编码前流程节点",
     ("scripts/tests/test_spec2code_workflow.py",), 180, 5000),
    ("Spec2Code 角色任务卡渲染",
     ("scripts/tests/test_role_task_documents.py",), 180, 5000),
    ("Spec2Code 角色任务卡 CLI",
     ("scripts/tests/test_role_task_cli.py",), 180, 5000),
    ("共享状态内核回归",
     ("scripts/tests/test_state_core.py",), 90, 3000),
    ("内嵌能力完整生命周期回归",
     ("scripts/tests/test_capabilities.py",), 240, 5000),
    ("内置规格引擎回归与差分对拍",
     ("scripts/tests/test_specengine.py",), 300, 5000),
    ("编译等待单次动作指令回归",
     ("scripts/tests/test_compile_wait_instructions.py",), 180, 5000),
    ("CodeCheck 全链路诊断日志回归",
     ("scripts/tests/test_codecheck_logging.py",), 180, 5000),
    ("UT 已有测试审计复用与收据回归",
     ("scripts/tests/test_ut_artifacts.py",), 180, 5000),
    ("轻量编码预检跨语言与安全降级回归",
     ("scripts/tests/test_lightcheck.py",), 180, 5000),
    ("轻量编码预检自动范围契约",
     ("scripts/tests/test_lightcheck_scope_contract.py",), 180, 5000),
    ("Workflow 定义与转移策略回归",
     ("scripts/tests/test_workflow_definition.py",), 180, 5000),
    ("Workflow 命令提示一致性红线",
     ("scripts/tests/test_command_prompt_agreement.py",), 180, 5000),
    ("Workflow 状态图活性红线",
     ("scripts/tests/test_flow_liveness.py",), 180, 5000),
    ("质量返工、检视、提交与月光闭环红线",
     ("scripts/tests/test_quality_flow_redlines.py",), 180, 5000),
    ("Gate 请求解析策略回归",
     ("scripts/tests/test_guard_intent.py",), 180, 5000),
    ("Gate 编辑裁决策略回归",
     ("scripts/tests/test_guard_gate.py",), 180, 5000),
    ("Gate 一次性放行令策略回归",
     ("scripts/tests/test_guard_permits.py",), 180, 5000),
    ("Gate 提交归属策略回归",
     ("scripts/tests/test_guard_ownership.py",), 180, 5000),
    ("Gate 通用 Bash 与 Git 策略回归",
     ("scripts/tests/test_guard_bash.py",), 180, 5000),
    ("质量任务卡纯契约回归",
     ("scripts/tests/test_quality_task_cards.py",), 180, 5000),
    ("质量任务卡应用用例回归",
     ("scripts/tests/test_quality_task_card_use_cases.py",), 180, 5000),
    ("CodeCheck 纯策略回归",
     ("scripts/tests/test_quality_codecheck.py",), 180, 5000),
    ("CodeCheck 执行用例回归",
     ("scripts/tests/test_quality_codecheck_use_cases.py",), 180, 5000),
    ("CodeCheck 范围与缓存状态回归",
     ("scripts/tests/test_quality_codecheck_state.py",), 180, 5000),
    ("CLI 命令路由契约回归",
     ("scripts/tests/test_command_dispatch.py",), 180, 5000),
    ("用户介入现场接纳与回退契约",
     ("scripts/tests/test_user_intervention.py",), 180, 5000),
    ("编码任务里程碑观察事件回归",
     ("scripts/tests/test_build_milestones.py",), 180, 5000),
    ("CLI 公共门面兼容回归",
     ("scripts/tests/test_cli_runtime_facade.py",), 180, 5000),
    ("重构架构边界",
     ("scripts/tests/test_architecture.py",), 180, 5000),
    ("重构完成契约与覆盖清单",
     ("scripts/tests/test_refactor_completion.py",), 180, 5000),
    ("故障注入与原子写失败回归",
     ("scripts/tests/test_fault_injection.py",), 180, 5000),
    ("Evidence 值对象与注册执行回归",
     ("scripts/tests/test_evidence.py",), 180, 5000),
    ("Agent 生命周期观察回归",
     ("scripts/tests/test_agent_observations.py",), 180, 5000),
    ("Agent Evidence 生命周期与检视回归",
     ("scripts/tests/test_agent_evidence.py",), 180, 5000),
    ("Delivery 不可变用例结果回归",
     ("scripts/tests/test_delivery_models.py",), 180, 5000),
    ("Delivery Standalone 生命周期用例回归",
     ("scripts/tests/test_delivery_standalone_use_cases.py",), 180, 5000),
    ("Delivery Moonlight 生命周期用例回归",
     ("scripts/tests/test_delivery_moonlight_use_cases.py",), 180, 5000),
    ("Hook transcript 工具证据回归",
     ("scripts/tests/test_hook_tool_transcript.py",), 180, 5000),
    ("Hook Agent 历史报告兼容回归",
     ("scripts/tests/test_hook_agent_reports.py",), 180, 5000),
    ("Hook 任务卡与源码范围契约回归",
     ("scripts/tests/test_hook_task_card_contracts.py",), 180, 5000),
    ("COMPILE 真实执行策略回归",
     ("scripts/tests/test_hook_compile_contract.py",), 180, 5000),
    ("GRILL 审查策略回归",
     ("scripts/tests/test_hook_grill_contract.py",), 180, 5000),
    ("CODECHECK 真实执行策略回归",
     ("scripts/tests/test_hook_codecheck_contract.py",), 180, 5000),
    ("UT 真实执行策略回归",
     ("scripts/tests/test_hook_unit_test_contract.py",), 180, 5000),
    ("云端形态:本地不编译不跑 UT(作弊守卫仍在)",
     ("scripts/tests/test_cloud_no_local_build.py",), 90, 3000),
    ("流水线证据口:终态严谨、宿主等待不死锁",
     ("scripts/tests/test_pipeline_evidence.py",), 90, 3000),
    ("流水线红灯:单次精确轻量修复不回人工卡",
     ("scripts/tests/test_external_repair.py",), 90, 3000),
    ("人工审批对象绑定稳定内容且可自动换卡",
     ("scripts/tests/test_approval_subject.py",), 90, 3000),
    ("宿主契约:steps --json 的交付方式目录与真流程一致",
     ("scripts/tests/test_steps_catalog.py",), 90, 3000),
    ("宿主契约:下单事实补配置、抑 Q2、workflow_select 免卡",
     ("scripts/tests/test_order_facts.py",), 90, 3000),
    ("Hook Agent 收尾编排回归",
     ("scripts/tests/test_hook_agent_completion.py",), 180, 5000),
    ("Hook 事件路由回归",
     ("scripts/tests/test_hook_events.py",), 180, 5000),
    ("Hook 协议适配回归",
     ("scripts/tests/test_hook_protocol.py",), 180, 5000),
)


def execute_refactor_safety_suites(
        root, python_executable, report, run=None):
    """Execute every registered suite and report every result immediately."""
    run = run or subprocess.run
    for label, command, timeout, output_limit in REFACTOR_SAFETY_SUITES:
        result = run(
            [
                python_executable,
                os.path.join(root, command[0]),
                *command[1:],
            ],
            text=True,
            encoding="utf-8",
            errors="replace",
            capture_output=True,
            check=False,
            timeout=timeout,
        )
        report(
            label,
            result.returncode == 0,
            (result.stdout + result.stderr)[-output_limit:],
        )
