/** Builds a local preview using the unchanged Archify renderer plus module details. */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, join } from 'node:path';
import { classifyStoryFixture } from './moduleRoles.ts';
import { compile } from './compile.ts';
import { renderArchify } from '../../src/archifyRender.ts';
const out=resolve(process.env.ARCHIFY_PROBE_OUT || '.local/archify-probe');
const names=['fast-1','fast-2','fast-3','semantic-1','semantic-2','semantic-3'];
const records=names.filter(n=>existsSync(join(out,`${n}.html`))).map(name=>({name,data:name==='fast-1'?classifyStoryFixture(JSON.parse(readFileSync(join(out,`${name}.json`),'utf8'))):JSON.parse(readFileSync(join(out,`${name}.json`),'utf8')),result:JSON.parse(readFileSync(join(out,`${name}.result.json`),'utf8'))}));
const decorate=(html:string)=>html.replace('</head>',`<style>.cards{display:none!important}.container{max-width:none!important}.diagram-container{min-height:530px}svg [data-node-label]{font-size:18px}svg [data-detail-anchor]{font-size:18px}svg text[data-detail="context"]{font-size:12px}</style></head>`).replace('</body>',`<script>document.addEventListener('click',e=>{const n=e.target.closest('[data-node-id]');if(n)parent.postMessage({kind:'module',id:n.dataset.nodeId},'*')});</script></body>`);
for(const r of records){
 const overview=await renderArchify(await compile(r.data,out));
 if(!overview.html) throw Error('Overview render failed: '+overview.error);
 writeFileSync(join(out,`${r.name}.interactive.html`),decorate(overview.html));
 for(const m of r.data.modules){
   const ids=new Set([m.id,...r.data.relations.filter((e:any)=>e.from===m.id||e.to===m.id).flatMap((e:any)=>[e.from,e.to])]);
   const subset={...r.data,title:m.name+' · 直接协作关系',modules:r.data.modules.filter((x:any)=>ids.has(x.id)),relations:r.data.relations.filter((e:any)=>ids.has(e.from)&&ids.has(e.to))};
   const result=await renderArchify(await compile(subset,out));
   if(!result.html) throw Error('Neighborhood render failed: '+result.error);
   writeFileSync(join(out,`${r.name}.${m.id}.html`),decorate(result.html));
 }
}
const input=readFileSync(join(out,'input.md'),'utf8');
for(const r of records)for(const m of r.data.modules)m.evidenceExact=input.includes(m.evidence);
const payload=JSON.stringify(records).replace(/</g,'\\u003c');
writeFileSync(join(out,'index.html'),`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>Archify 本地验证 · 模块职责与协作</title><style>
*{box-sizing:border-box}body{margin:0;background:#f3f5f9;color:#18273b;font:16px/1.6 system-ui,sans-serif}header{height:164px;padding:20px 32px;background:white;border-bottom:1px solid #dce3ee}h1{font-size:25px;margin:0}header p{margin:5px 0;color:#59677b}.bar{display:flex;align-items:center;gap:16px;margin-top:10px}select,button{font:inherit;padding:7px 13px;border:1px solid #ccd7e7;border-radius:8px;background:white;color:#243953;cursor:pointer}.badge{color:#176346;background:#e4f5ec;padding:5px 12px;border-radius:6px}.layout{display:grid;grid-template-columns:minmax(0,1fr) 370px;gap:18px;padding:20px 26px}iframe{width:100%;height:760px;border:0;border-radius:12px;background:#101620}aside{background:white;border:1px solid #dce3ee;border-radius:12px;padding:22px;overflow:auto;max-height:760px}h2{font-size:21px;margin:0 0 12px}h3{font-size:15px;color:#697b93;margin:20px 0 4px}p{margin:4px 0;white-space:pre-wrap}.tabs{display:flex;gap:7px;flex-wrap:wrap;margin-bottom:18px}.tabs button{font-size:13px;padding:4px 8px}.tabs button.active{background:#e9f0ff;color:#235fc1;border-color:#86aae5}.source{font-size:14px;color:#637089;border-left:3px solid #dce3ee;padding-left:12px}.note{font-size:13px;color:#738198}a{color:#225fc0}details{border-top:1px solid #e4e9f0;margin-top:20px;padding-top:14px}summary{cursor:pointer;font-size:16px;font-weight:600}#summary{font-size:19px;line-height:1.7;color:#215b8b;margin-bottom:22px}#relations{font-size:15px;line-height:2}details p{font-size:15px;margin-top:12px}</style>
<header><h1>整体 Story · 模块职责与协作</h1><p>先看模块如何协作，点击模块了解它具体负责什么。</p><div class="bar"><select id="run"></select><button id="overview">查看全部关系</button><span id="scope" class="note"></span><span class="badge" id="metrics"></span><span class="note">本地实验｜来源 docs/overall-story.md｜连线表示协作，不表示任务串行</span><a href="input.md" target="_blank">查看原始材料</a></div></header>
<div class="layout"><iframe id="diagram" title="Archify 模块图" sandbox="allow-scripts allow-downloads"></iframe><aside><div class="tabs" id="modules"></div><h2 id="name"></h2><p id="summary"></p><h3>如何协作</h3><p id="relations"></p><details><summary>工作内容与交付</summary><h3>具体职责</h3><p id="responsibility"></p><h3>接口与交付材料</h3><p id="interfaces"></p></details><details><summary>验收要求</summary><p id="acceptance"></p></details><details><summary>查看原文依据</summary><p class="source" id="evidence"></p></details></aside></div>
<script>const records=${payload};let current;const el=id=>document.getElementById(id);function show(id){el('diagram').src=current.name+'.'+id+'.html';el('scope').textContent='当前：所选模块及其直接协作方';const m=current.data.modules.find(x=>x.id===id);if(!m)return;document.querySelectorAll('aside details').forEach(d=>d.open=false);for(const key of ['name','summary','responsibility','interfaces','acceptance','evidence'])el(key).textContent=m[key];el('evidence').textContent=(m.evidenceExact?'原文引用：':'模型概括，需核对原文：')+m.evidence;el('relations').textContent=current.data.relations.filter(e=>e.from===id||e.to===id).map(e=>current.data.modules.find(m=>m.id===e.from).name+' → '+current.data.modules.find(m=>m.id===e.to).name+'：'+e.label).join('\\n');for(const b of el('modules').children)b.classList.toggle('active',b.dataset.id===id)}function load(){current=records[Number(el('run').value)];el('diagram').src=current.name+'.interactive.html';el('modules').replaceChildren();for(const m of current.data.modules){const b=document.createElement('button');b.textContent=m.name;b.dataset.id=m.id;b.onclick=()=>show(m.id);el('modules').append(b)}el('metrics').textContent=current.data.modules.length+' 个模块 · '+current.data.relations.length+' 条关系 · 渲染成功';show(current.data.modules[0].id)}records.forEach((r,i)=>{const o=document.createElement('option');o.value=i;o.textContent=(r.name.startsWith('fast')?'精炼版 ':'初版 ')+r.name.split('-')[1];el('run').append(o)});el('run').onchange=load;el('overview').onclick=()=>{el('diagram').src=current.name+'.interactive.html';el('scope').textContent='当前：全部模块与关系，可缩放';};window.addEventListener('message',e=>{if(e.source===el('diagram').contentWindow&&e.data?.kind==='module')show(e.data.id)});if(records.length)load();</script></html>`);
console.log(join(out,'index.html'));
