import { KnowledgeSourceCleanup } from "./KnowledgeSourceCleanup";
import { KnowledgeResearchProgress } from "./KnowledgeResearchProgress";
import { DomainKnowledgeArchiveTargets } from "./DomainKnowledgeArchiveTargets";
import { DomainKnowledgeFileTree } from "./DomainKnowledgeFileTree";
import { KnowledgeMarkdown, type KnowledgeFocus } from "./KnowledgeMarkdown";
import { resolveKnowledgeReference } from "./knowledgeStructure";
import { KnowledgeCleanupOptions } from "./KnowledgeCleanupOptions";
import { getBusinessModules, type BusinessModule } from "./api";
import { useEffect, useRef, useState } from "react";
import { diffLines } from "diff";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { KnowledgeExtractionWorkspace, KnowledgeExtractionStages } from "./KnowledgeExtractionWorkspace";
import { ExtractionSkillEditor } from "./ExtractionSkillEditor";
import { KnowledgeMaterialUpload, type MaterialSummary } from "./KnowledgeMaterialUpload";
import { componentRequest } from "./componentResearchApi";
import { Markdown } from "./markdown";
import type { DomainKnowledgeJob, DomainDocument } from "../../src/domainKnowledgeTypes";

const body = (doc: { content: string; sources: string }) => `${doc.content}\n\n## 来源\n\n${doc.sources}`;
export function DomainKnowledgeExtraction({ focusId }: { focusId?: string }) {
  const [records, setRecords] = useState<DomainKnowledgeJob[]>([]), [job, setJob] = useState<DomainKnowledgeJob>(), [selected, setSelected] = useState(new URLSearchParams(location.search).get("domainExtraction") ?? "");
  const selectedRef = useRef(selected);
  const [deleting, setDeleting] = useState(false);
  const [open, setOpen] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const [modules, setModules] = useState<BusinessModule[]>([]), [moduleId, setModuleId] = useState("");
  const [issueNo, setIssueNo] = useState(""), [legacyIssueNo, setLegacyIssueNo] = useState("");
  const [baselineBranch, setBaselineBranch] = useState("master");
  const module = modules.find(item => item.id === moduleId);
  const [materials, setMaterials] = useState<MaterialSummary[]>([]), [uploading, setUploading] = useState(false), [arCodes, setArCodes] = useState("");
  const [extraMaterials, setExtraMaterials] = useState<MaterialSummary[]>([]), [extraArCodes, setExtraArCodes] = useState("");
  const [archiveBlocked, setArchiveBlocked] = useState(false);
  const [cleanupBlocked, setCleanupBlocked] = useState<Record<string, boolean>>({});
  const [knowledgeFocus, setKnowledgeFocus] = useState<KnowledgeFocus>();
  const [related, setRelated] = useState(false);
  const [documentId, setDocumentId] = useState(""), [tab, setTab] = useState<"content" | "diff" | "history" | "sources" | "remote">("content"), [stage, setStage] = useState("review");
  const [message, setMessage] = useState(""), [latest, setLatest] = useState(false), [edit, setEdit] = useState<DomainDocument>();
  const currentStage = stage;
  useEffect(() => { if (job?.source_cleanup && !job.source_cleanup.started) setStage("cleanup"); }, [job?.id]);
  const active = job && ["queued", "running"].includes(job.status), document = job?.documents.find(d => d.id === documentId) ?? job?.documents[0];
  const turns = job?.turns.filter(t => t.document_ids.includes(document?.id ?? "")) ?? [];
  const proposalTurn = [...turns].reverse().find(t => t.proposals.some(p => p.document.id === document?.id && p.status === "pending"));
  const proposal = proposalTurn?.proposals.find(p => p.document.id === document?.id && p.status === "pending");
  function navigateKnowledge(id: string, line?: number, anchor?: string) {
    if (edit?.id === id && (line !== undefined || !!anchor)) { setError("请先保存或取消当前编辑，再跳转章节。"); return; }
    setDocumentId(id); setTab("content"); setMessage(""); setError("");
    setKnowledgeFocus(old => ({ line, anchor, token: (old?.token ?? 0) + 1 }));
  }
  async function refreshList() { const result = await componentRequest<{ records: DomainKnowledgeJob[] }>("/domain-extraction"); setRecords(result.records); }
  useEffect(() => { void getBusinessModules().then(result => setModules(result.modules.filter(m => m.status === "active"))).catch(e => setError(e.message)); void refreshList().catch(e => setError(e.message)); }, []);
  useEffect(() => {
    if (!selected) return; let live = true;
    const load = async () => { try { const next = await componentRequest<DomainKnowledgeJob>(`/domain-extraction/${selected}`); if (live && selectedRef.current === selected) setJob(next); } catch (e) { if (live && selectedRef.current === selected) setError((e as Error).message); } };
    void load(); const timer = setInterval(() => void load(), 4000); return () => { live = false; clearInterval(timer); };
  }, [selected]);
  function select(id: string) { selectedRef.current = id; setDeleting(false); setSelected(id); setJob(undefined); setDocumentId(""); setEdit(undefined); setMessage(""); setExtraMaterials([]); setExtraArCodes(""); setLegacyIssueNo(""); setCleanupBlocked({}); setArchiveBlocked(false); const url = new URL(location.href); if (id) url.searchParams.set("domainExtraction", id); else url.searchParams.delete("domainExtraction"); history.replaceState(history.state, "", url); }
  useEffect(() => { if (focusId) select(focusId); }, [focusId]);
  async function action(name: string, input: unknown = {}) {
    if (!job) return false; setBusy(true); setError("");
    try { setJob(await componentRequest<DomainKnowledgeJob>(`/domain-extraction/${job.id}/${name}`, input)); await refreshList(); return true; }
    catch (e) { setError((e as Error).message); return false; } finally { setBusy(false); }
  }
  async function remove() {
    if (!job) return;
    const id = job.id; setBusy(true); setError("");
    try {
      await componentRequest<{ deleted: boolean }>(`/domain-extraction/${id}/delete`, {});
      if (selectedRef.current === id) select("");
      setRecords(current => current.filter(record => record.id !== id));
    } catch (error) { setError((error as Error).message); } finally { setBusy(false); }
  }
  async function run(mode: "discuss" | "revise" | "update") {
    if (document && await action("run", { mode, document_ids: related ? job!.documents.filter(d => d.selected).map(d => d.id) : [document.id], message, use_latest_skill: latest })) setMessage("");
  }
  return <KnowledgeExtractionWorkspace cleanup title="领域知识萃取" onNew={() => setOpen(true)} actions={<ExtractionSkillEditor kind="domain" />}
    sidebar={<div className="space-y-2">{records.map(record => <button key={record.id} className={`w-full rounded-lg border p-3 text-left ${selected === record.id ? "border-primary bg-primary/5" : "border-line"}`} onClick={() => select(record.id)}><strong className="block">{record.title}</strong><span className="mt-2 block text-sm text-muted-foreground">{record.repositories.length} 个业务仓 · {record.stage}</span></button>)}{!records.length && <p className="text-muted-foreground">暂无领域萃取记录</p>}</div>}>
    {error && <p role="alert" className="mb-3 text-danger">{error}</p>}
    {job ? <><header className="mb-4 flex items-start gap-3"><div className="mr-auto"><h3 className="text-xl font-semibold">{job.title}</h3><p className="mt-1 text-sm text-muted-foreground">关联单号：{job.issue_no || "待补充"}</p><p className="mt-2 text-primary">{job.stage}</p>{job.skill && <p className="mt-1 text-xs text-muted-foreground">{job.skill.name} · {job.skill.digest.slice(0, 12)}</p>}</div>
      {active ? <Button variant="outline" disabled={busy} onClick={() => void action("stop")}>停止本轮</Button> : ["failed", "cancelled"].includes(job.status) && <Button variant="outline" disabled={busy} onClick={() => { const last = job.turns.at(-1); void action("run", { mode: last?.mode ?? "extract", document_ids: last?.document_ids, message: last?.message ?? job.scope }); }}>重试未完成研究</Button>}<Button variant="outline" disabled={busy} onClick={() => { setError(""); setDeleting(true); }}>删除任务</Button></header>
      {!job.issue_no && <div className="mb-4 flex items-end gap-3"><label className="grid gap-1">关联单号<Input value={legacyIssueNo} maxLength={120} onChange={e => setLegacyIssueNo(e.target.value)} placeholder="创建 MR 前请补充单号" /></label><Button disabled={busy || !legacyIssueNo.trim()} onClick={() => void action("issue", { issue_no: legacyIssueNo })}>保存关联单号</Button></div>}
      {job.error && <p className="mb-3 text-danger">{job.error}</p>}
      <KnowledgeExtractionStages cleanup value={currentStage} onChange={setStage} label="领域萃取阶段" />
      {currentStage === "cleanup" && <KnowledgeSourceCleanup key={job.id} task={job} endpoint={`/domain-extraction/${job.id}`} onChange={setJob} onStarted={() => { setStage("progress"); void refreshList(); }} />}
      {currentStage === "inputs" && <div className="space-y-4"><p>{job.scope}</p>{(job.source_repositories ?? job.repositories).map(repo => <div key={repo.id} className="rounded border border-line p-3 text-sm"><strong>{repo.name}</strong><p className="break-all">{repo.repository} · {repo.branch} · {repo.path || "全仓"}</p><p>读取版本：{job.revisions[repo.id]?.slice(0, 12) ?? "未读取"}</p></div>)}<p>关联业务 AR：{job.ar_codes.join("、") || "未指定"}</p><p>已关联 {job.material_ids.length} 份上传资料</p><KnowledgeMaterialUpload materials={extraMaterials} onChange={setExtraMaterials} onBusy={setUploading} /><label className="grid gap-1">补充或调整 AR<Input value={extraArCodes} onChange={e => setExtraArCodes(e.target.value)} placeholder="多个编号用逗号分隔" /></label><Button disabled={busy || uploading || active || !document} onClick={() => void action("run", { mode: "update", document_ids: job.documents.map(d => d.id), message: "核对补充资料与当前来源，更新受影响文档；未变化内容保留", material_ids: [...new Set([...job.material_ids, ...extraMaterials.map(m => m.id)])], ar_codes: extraArCodes.trim() ? extraArCodes.split(/[,，\s]+/).filter(Boolean) : job.ar_codes, use_latest_skill: latest })}>用补充资料生成更新建议</Button></div>}
      {currentStage === "progress" && <KnowledgeResearchProgress key={job.id} evidence={job.evidence} />}
      {currentStage === "review" && (!job.source_cleanup || job.source_cleanup.started) && <section className="research-review" aria-label="领域知识审查工作区"><div className="research-review-toolbar"><strong className="mr-auto">{job.documents.length} 份草稿 · {job.documents.filter(d => d.selected).length} 份已选</strong><span className="text-sm text-muted-foreground">选择文件查看正文，归档位置在「入库与更新」调整</span></div><div className="research-review-panes">
        <DomainKnowledgeFileTree job={job} currentId={document?.id} onNavigate={navigateKnowledge} disabled={busy || active} onSelection={(id, selected) => void action("selection", { ids: [id], selected })} />
        <div className="research-reader">{document ? <><div className="research-document-content"><p className="mb-3 text-sm font-medium">{[job.knowledge_target, ...job.repositories].find(target => target.id === document.target_id)?.name} / {document.path.split("/").at(-1)} · 修订 {document.revision}</p><div className="mb-3 flex flex-wrap gap-2">{([["content", "正文"], ["diff", "差异"], ["sources", "来源"], ["history", "历史"], ["remote", "远端合并"]] as const).map(([value, label]) => <Button key={value} size="sm" variant={tab === value ? "default" : "outline"} onClick={() => setTab(value)}>{label}</Button>)}<Button size="sm" variant="outline" onClick={() => { setEdit(structuredClone(document)); setTab("content"); }}>编辑</Button></div>
          {tab === "content" && (edit?.id === document.id ? <div className="space-y-3"><Input aria-label="文档标题" value={edit.title} onChange={e => setEdit({ ...edit, title: e.target.value })} /><Textarea aria-label="编辑领域文档" rows={20} value={edit.content} onChange={e => setEdit({ ...edit, content: e.target.value })} /><Textarea aria-label="编辑文档来源" rows={5} value={edit.sources} onChange={e => setEdit({ ...edit, sources: e.target.value })} /><Button disabled={busy} onClick={async () => { if (await action("edit", { document: edit, base_revision: edit.revision })) setEdit(undefined); }}>保存人工版本</Button><Button variant="outline" onClick={() => setEdit(undefined)}>取消</Button></div> : <KnowledgeMarkdown text={document.content} focus={knowledgeFocus} onReference={href => {
            const found = resolveKnowledgeReference(job.documents, document, href);
            if (!found) return false; navigateKnowledge(found.item.id, undefined, found.anchor); return true;
          }} />)}
          {tab === "sources" && <Markdown text={document.sources} />}
          {tab === "remote" && <div className="space-y-4"><p className="text-sm">读取目标分支与当前 MR 的真实内容，核对后编辑合并稿。提交前会再次检查远端，新的修改仍会阻止覆盖。</p><Button variant="outline" disabled={busy} onClick={async () => { if (await action("remote", { document_id: document.id })) setEdit(current => current?.id === document.id ? current : structuredClone(document)); }}>读取远端版本并比较</Button>
            {document.remote_review && <><p className="text-xs text-muted-foreground">目标版本 {document.remote_review.target_revision.slice(0, 12)}{document.remote_review.branch_revision && ` · MR 版本 ${document.remote_review.branch_revision.slice(0, 12)}`} · {document.remote_review.reviewed ? "已人工核对" : "待人工核对"}</p>
              <details open><summary>目标分支与当前草稿的差异</summary><pre className="whitespace-pre-wrap break-words text-sm">{diffLines(document.remote_review.target_content ?? "", body(document)).map((part, i) => <span key={i} className={part.added ? "bg-green-500/15" : part.removed ? "bg-red-500/15 line-through" : ""}>{part.value}</span>)}</pre></details>
              {document.remote_review.branch && <details open><summary>当前 MR 分支原文</summary><pre className="whitespace-pre-wrap break-words text-sm">{document.remote_review.branch_content ?? "此文件不存在"}</pre></details>}
              <label className="grid gap-2">人工合并后的正文<Textarea aria-label="远端合并稿" rows={14} value={edit?.id === document.id ? edit.content : document.content} onChange={e => setEdit({ ...(edit?.id === document.id ? edit : structuredClone(document)), content: e.target.value })} /></label>
              <label className="grid gap-2">合并后的来源<Textarea aria-label="远端合并来源" rows={4} value={edit?.id === document.id ? edit.sources : document.sources} onChange={e => setEdit({ ...(edit?.id === document.id ? edit : structuredClone(document)), sources: e.target.value })} /></label>
              <Button disabled={busy} onClick={async () => { if (await action("reconcile", { document: edit?.id === document.id ? edit : document, base_revision: edit?.id === document.id ? edit.revision : document.revision, snapshot_id: document.remote_review!.id })) setEdit(undefined); }}>保存合并稿并确认远端版本</Button>
            </>}
          </div>}
          {tab === "diff" && (proposal ? <><p className="mb-3 text-sm">建议基于 v{proposal.base_revision}，当前 v{document.revision}。{proposal.base_revision !== document.revision && "正文已修改，请重新生成或手工合并。"}</p><pre className="whitespace-pre-wrap break-words text-sm">{diffLines(body(document), body(proposal.document)).map((part, i) => <span key={i} className={part.added ? "bg-green-500/15" : part.removed ? "bg-red-500/15 line-through" : ""}>{part.value}</span>)}</pre><div className="mt-4 flex gap-2"><Button disabled={busy || document.revision !== proposal.base_revision} onClick={() => void action("proposal", { turn_id: proposalTurn!.id, document_id: document.id, decision: "accept" })}>采纳建议</Button><Button variant="outline" disabled={busy} onClick={() => void action("proposal", { turn_id: proposalTurn!.id, document_id: document.id, decision: "discard" })}>放弃</Button></div></> : <p>没有待采纳建议。</p>)}
          {tab === "history" && <div className="space-y-3">{[...document.history].reverse().map(h => <details key={h.revision}><summary>v{h.revision} · {h.operator} · {new Date(h.at).toLocaleString()}</summary><Markdown text={body(h)} /><Button disabled={busy} onClick={() => void action("restore", { document_id: document.id, revision: h.revision, base_revision: document.revision })}>恢复为新版本</Button></details>)}{!document.history.length && <p>尚无历史版本。</p>}</div>}
        </div><section className="research-discussion"><h4 className="font-semibold">与 AI 讨论 · {document.title}</h4><p className="mt-2 text-sm text-muted-foreground">讨论保留原稿。修订和更新生成建议，采纳后才进入归档内容。</p><div className="my-4 space-y-4">{turns.map(turn => <article key={turn.id} className="border-b border-line pb-3 text-sm"><p className="mb-1 text-xs text-muted-foreground">{turn.operator}{turn.skill && ` · Skill ${turn.skill.digest.slice(0, 8)}`}</p><p className="whitespace-pre-wrap">{turn.message}</p>{turn.reply && <Markdown text={turn.reply} />}{turn.error && <p className="text-danger">{turn.error}</p>}<p className="text-muted-foreground">{turn.status === "running" ? "正在查证…" : turn.status === "queued" ? "等待执行" : turn.status === "done" ? "本轮完成" : turn.status === "cancelled" ? "已停止" : "本轮失败"}</p>{turn.proposals.some(p => p.document.id === document.id && p.status === "pending") && <Button variant="link" onClick={() => setTab("diff")}>比较修订建议</Button>}</article>)}</div><label className="mb-3 flex items-center gap-2 text-sm"><input type="checkbox" checked={latest} onChange={e => setLatest(e.target.checked)} />下一轮用最新领域 Skill</label><label className="mb-3 flex items-center gap-2 text-sm"><input type="checkbox" checked={related} onChange={e => setRelated(e.target.checked)} />同时处理已勾选的关联文档</label><Textarea aria-label="领域知识修订意见" rows={5} value={message} onChange={e => setMessage(e.target.value)} placeholder="补充问题、纠正业务规则或说明更新范围…" /><div className="mt-3 flex flex-wrap gap-2"><Button variant="outline" disabled={busy || active || !message.trim()} onClick={() => void run("discuss")}>仅讨论</Button><Button disabled={busy || active || !message.trim()} onClick={() => void run("revise")}>生成建议</Button><Button variant="outline" disabled={busy || active || !message.trim()} onClick={() => void run("update")}>核对来源更新</Button></div></section></> : <p className="p-5">研究完成的文档会逐步显示在这里。</p>}</div>
      </div></section>}
      {currentStage === "publish" && <div className="space-y-4"><DomainKnowledgeArchiveTargets job={job} disabled={busy || active || !!edit} onChange={setJob} onBlockedChange={setArchiveBlocked} onCompare={id => { setDocumentId(id); setTab("remote"); setStage("review"); }} />{edit && <p className="text-sm text-muted-foreground">请先保存或取消正文编辑，再调整归档位置。</p>}{[job.knowledge_target, ...job.repositories].filter(target => job.documents.some(doc => doc.selected && doc.target_id === target.id)).map(target => <KnowledgeCleanupOptions key={`${job.id}:${target.id}:${job.archive_revision ?? 0}`} job={job} target={target} endpoint={`/domain-extraction/${job.id}`} disabled={busy || active || archiveBlocked || job.archive_configured === false} onChange={setJob} onBlockedChange={blocked => setCleanupBlocked(current => current[target.id] === blocked ? current : { ...current, [target.id]: blocked })} />)}<p>按目标仓创建 MR；未合入时继续更新同一 MR，合入后更新会创建新 MR。合入后同步正式知识文档，索引状态在知识文档页查看。</p><p className="text-sm">本次归档 {job.documents.filter(d => d.selected).length} 份当前草稿，涉及 {new Set(job.documents.filter(d => d.selected).map(d => d.target_id)).size} 个目标仓。未采纳的建议不进入 MR。</p><ul className="space-y-1 text-sm text-muted-foreground">{job.documents.filter(d => d.selected).map(d => <li key={d.id}>{[job.knowledge_target, ...job.repositories].find(r => r.id === d.target_id)?.name} / {d.path} · v{d.revision}</li>)}</ul><div className="flex gap-3"><Button disabled={busy || active || archiveBlocked || job.archive_configured === false || job.documents.some(d => d.selected && cleanupBlocked[d.target_id]) || !job.documents.some(d => d.selected)} onClick={() => void action("publish")}>{busy ? "处理中…" : "一键创建或更新 MR"}</Button><Button variant="outline" disabled={busy} onClick={() => void action("refresh")}>刷新合入状态并入库</Button></div>{[...job.publications, ...(job.publication_history ?? [])].map(p => <article key={p.branch} className="rounded-lg border border-line p-4"><strong>{[job.knowledge_target, ...job.repositories].find(r => r.id === p.target_id)?.name}</strong><p className="mt-2">{({ pending: "归档准备中", opened: "MR 待合入", merged: "MR 已合入", failed: "归档失败，可重试", closed: "MR 已关闭", unchanged: "目标文档没有变化，无需创建 MR" })[p.state]}</p>{p.url && <a href={p.url} target="_blank" rel="noreferrer" className="text-primary underline">查看 MR ↗</a>}{p.sync_state && <p>{p.sync_state === "done" ? "正式知识文档已同步，索引状态另行展示" : p.sync_state === "failed" ? `知识文档同步失败：${p.sync_error}` : "知识文档待同步"}</p>}{p.error && <p className="text-danger">{p.error}</p>}<ul className="mt-2 text-sm text-muted-foreground">{p.documents.map(d => <li key={d.id}>{d.path} · v{d.revision}</li>)}</ul></article>)}</div>}
    </> : <p className="p-8 text-muted-foreground">{selected ? "正在加载任务…" : "选择历史任务，或新建领域萃取。"}</p>}
    <Dialog open={deleting} onOpenChange={setDeleting}><DialogContent className="tw-root sm:max-w-[480px]"><DialogHeader><DialogTitle>删除领域萃取任务？</DialogTitle></DialogHeader><p className="font-medium">{job?.title}</p><p className="text-sm text-muted-foreground">任务及草稿将从萃取列表移除，正在执行的研究会停止。已创建的 MR、仓库文件和已入库的知识文档会保留，来源记录保留用于追溯。</p>{error && <p role="alert" className="text-danger">{error}</p>}<div className="flex justify-end gap-3"><Button variant="outline" disabled={busy} onClick={() => setDeleting(false)}>取消</Button><Button variant="destructive" disabled={busy} onClick={() => void remove()}>确认删除</Button></div></DialogContent></Dialog>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="tw-root sm:max-w-[850px] max-h-[90vh] overflow-auto"><DialogHeader><DialogTitle>新建领域知识萃取</DialogTitle></DialogHeader>{error && <p role="alert" className="text-danger">{error}</p>}<div className="space-y-5"><label className="grid gap-2">业务模块<select aria-label="萃取业务模块" className="rounded border border-line bg-surface p-2" value={moduleId} onChange={e => setModuleId(e.target.value)}><option value="">请选择业务模块</option>{modules.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><p className="text-sm text-muted-foreground">按照领域萃取 Skill 完整研究所选业务模块，代码仓统一从业务模块维护中读取。</p>{module && <p className="text-sm">{module.name} · 已关联 {module.repositories.length} 个代码仓{!module.repositories.length && "，请先在业务模块中维护"}</p>}<label className="grid gap-2">统一基准分支<Input aria-label="统一基准分支" value={baselineBranch} onChange={e => setBaselineBranch(e.target.value)} placeholder="master" /><span className="text-sm text-muted-foreground">本次关联仓库统一读取此分支。</span></label><label className="grid gap-2">关联单号（必填）<Input aria-label="领域萃取关联单号" required maxLength={120} value={issueNo} onChange={e => setIssueNo(e.target.value)} placeholder="填写本次知识归档关联的需求或问题单号" /><span className="text-sm text-muted-foreground">本任务创建的所有 MR 关联此单号。</span></label><p className="text-sm text-muted-foreground">归档仓和文档目录在「入库与更新」选择，系统会带出默认位置。</p><KnowledgeMaterialUpload materials={materials} onChange={setMaterials} onBusy={setUploading} /><details className="text-sm"><summary className="cursor-pointer">补充业务 AR（可选）</summary><Input className="mt-2" aria-label="关联业务 AR" value={arCodes} onChange={e => setArCodes(e.target.value)} placeholder="已知相关 AR 时填写，多个编号用逗号分隔" /></details><Button disabled={busy || uploading || !issueNo.trim() || !module?.repositories.length || !baselineBranch.trim()} onClick={async () => { setBusy(true); setError(""); try { const next = await componentRequest<DomainKnowledgeJob>("/domain-extraction", { issue_no: issueNo, module_id: moduleId, baseline_branch: baselineBranch, material_ids: materials.map(m => m.id), ar_codes: arCodes.split(/[,，\s]+/).filter(Boolean) }); select(next.id); setJob(next); setStage(next.source_cleanup ? "cleanup" : "progress"); setOpen(false); await refreshList(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }}>创建任务，先清理旧知识</Button></div></DialogContent></Dialog>
  </KnowledgeExtractionWorkspace>;
}
