"""Stable facade for Mae-Flow's pure-Python specification engine."""

from . import specengine_archive as _archive_impl
from .specengine_base import (
    DEFAULT_SCHEMA,
    LEGACY_SPEC_WORKSPACE,
    SPEC_WORKSPACE_RELATIVE,
    PLUGIN_ROOT,
    VENDOR_SCHEMAS_DIR,
    SpecEngineError,
    _ANY_HEADER_RE,
    _CHANGE_NAME_RE,
    _CONFIG_TEMPLATE_LINES,
    _DATE_RE,
    _DELTA_HEADER_RE,
    _HAS_DELTA_RE,
    _HEADER_LINE_RE,
    _LEAK_RE,
    _METADATA_LINE_RE,
    _REMOVED_BULLET_RE,
    _RENAME_FROM_RE,
    _RENAME_TO_RE,
    _REQUIREMENTS_SECTION_RE,
    _REQ_HEADER_RE,
    _REQ_HEADER_STRICT_RE,
    _SCENARIO_ANY_RE,
    _SCENARIO_NAMED_RE,
    _SECTION_H2_RE,
    _SHALL_RE,
    _TASK_DONE_RE,
    _TASK_RE,
    _TOP_LEVEL_SECTION_RE,
    _archive_dir,
    _change_dir,
    _changes_dir,
    _list_active_changes,
    _main_specs_dir,
    _norm_newlines,
    _openspec_dir,
    _posix,
    _read_text,
    _read_text_utf8,
    _rel_under,
    _require_change_dir,
    _utc_today,
    _validate_change_name,
    _yaml_block_scalar,
    _yaml_indent,
    _yaml_is_noise,
    _yaml_load,
    _yaml_parse_list,
    _yaml_parse_mapping,
    _yaml_parse_value,
    _yaml_scalar,
    _yaml_unquote,
    atomic_write_text,
    datetime,
    os,
    re,
    shutil,
    time,
    timezone,
)
from .specengine_config import (
    _config_path,
    _list_vendored_schemas,
    _load_schema,
    _load_template,
    _read_change_metadata,
    _read_project_config,
    _resolve_schema_name,
)
from .specengine_markdown import (
    _build_code_fence_mask,
    _contains_shall_or_must,
    _count_scenarios,
    _extract_requirement_body,
    _extract_requirements_section,
    _find_main_spec_structure_issues,
    _find_section,
    _parse_delta_spec,
    _parse_removed_names,
    _parse_renamed_pairs,
    _parse_requirement_blocks,
    _parse_scenario_blocks,
    _parse_section_tree,
    _section_case_insensitive,
    _split_top_level_sections,
    _strip_fenced_blocks_preserving_lines,
    _validate_main_spec_content,
)
from .specengine_v5 import (
    CHANGE_DOC_NAME,
    V5_SECTION_DESIGN,
    V5_SECTION_SPEC,
    V5_SECTION_TASKS,
    V5_SECTION_WHY,
    V5_TIERS,
    V5_TIER_REQUIRED,
    _V5_H1_RE,
    _V5_SPEC_HEAD_RE,
    _build_change_skeleton,
    _change_doc_path,
    _change_layout,
    _collect_v5_structural_issues,
    _find_delta_spec_files,
    _has_delta_specs,
    _iter_delta_validation_sources,
    _legacy_markers,
    _parse_change_doc,
    _read_change_doc,
    _require_layout_pure,
    _shall_error_text,
    _validate_v5_domain,
)
from .specengine_validation import (
    _LEVEL_PREFIX,
    _collect_delta_issues,
    _format_issues,
    check_required_sections,
    has_delta,
    tasks_source,
    validate,
)
from .specengine_lifecycle import (
    _artifact_outputs,
    _build_order,
    _count_task_lines,
    _count_tasks,
    _detect_completed,
    _ensure_base_dirs,
    _list_main_spec_domains,
    _render_change_instructions,
    ensure_config,
    instructions,
    new_change,
    status,
)
from .specengine_archive_render import (
    _build_spec_skeleton,
    _build_updated_spec,
)
from .specengine_archive import (
    _find_spec_updates,
    _move_directory,
    _sweep_main_specs_for_leak,
)


def archive(root, change, date=None):
    """Archive a change while retaining the historical failure-injection seam."""
    _archive_impl._move_directory = _move_directory
    return _archive_impl.archive(root, change, date=date)
